--liquibase formatted sql
--changeset author:Artyom 3-create-subscription-tables

CREATE TABLE SUBSCRIPTION (
    ID          UUID,
    TITLE       VARCHAR(30)  NOT NULL,
    DESCRIPTION VARCHAR(100) NULL,
    PRIMARY KEY (ID),
    UNIQUE (TITLE)
);
COMMENT ON TABLE SUBSCRIPTION IS 'Информация о подписке';

CREATE TABLE ACCOUNT_SUBSCRIPTION (
    ACCOUNT_ID      UUID NOT NULL,
    SUBSCRIPTION_ID UUID NOT NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID),
    FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (ID),
    UNIQUE (ACCOUNT_ID, SUBSCRIPTION_ID)
);
COMMENT ON TABLE ACCOUNT_SUBSCRIPTION IS 'Таблица для связи таблиц SUBSCRIPTION и ACCOUNT';